source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

project 'ArtikCloudClient'
use_frameworks!

target 'ArtikCloudClientTests' do
  pod 'AFNetworking', '~> 3'
  pod 'ArtikCloud', :path => '../'  
end