source 'https://github.com/CocoaPods/Specs.git'

target 'ArtikCloudClient', :exclusive => true do
  pod "ArtikCloud", :path => "../"
end

target 'ArtikCloudClientTests', :exclusive => true do
  pod "ArtikCloud", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
