#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

#import "ACTag.h"


@protocol ACDeviceType
@end

@interface ACDeviceType : ACObject

/* Device Type ID. [optional]
 */
@property(nonatomic) NSString* _id;
/* Unique Name. [optional]
 */
@property(nonatomic) NSString* uniqueName;
/* Latest Manifest version. [optional]
 */
@property(nonatomic) NSNumber* latestVersion;

@property(nonatomic) NSNumber* lastUpdated;
/* Name. [optional]
 */
@property(nonatomic) NSString* name;
/* Description. [optional]
 */
@property(nonatomic) NSString* _description;
/* User ID. [optional]
 */
@property(nonatomic) NSString* uid;
/* Organization ID. [optional]
 */
@property(nonatomic) NSString* oid;
/* Uses Cloud Connectors SDK [optional]
 */
@property(nonatomic) NSNumber* hasCloudConnector;
/* Approval status. [optional]
 */
@property(nonatomic) NSNumber* approved;
/* Published status. [optional]
 */
@property(nonatomic) NSNumber* published;
/* Protected status. [optional]
 */
@property(nonatomic) NSNumber* protected;
/* In Store. [optional]
 */
@property(nonatomic) NSNumber* inStore;
/* Does the current user own a device of this device type [optional]
 */
@property(nonatomic) NSNumber* ownedByCurrentUser;
/* Tags [optional]
 */
@property(nonatomic) NSArray<ACTag>* tags;
/* Require Secure Device Registration (SDR) Protocol. [optional]
 */
@property(nonatomic) NSNumber* rsp;
/* Issuer Distinguished Name (Used in SDR) [optional]
 */
@property(nonatomic) NSString* issuerDn;
/* Vendor ID. (Used in SDR) [optional]
 */
@property(nonatomic) NSString* vid;

@end
