#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
* ARTIK Cloud API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/



@protocol ACDevice
@end

@interface ACDevice : ACObject

/* Device ID [optional]
 */
@property(nonatomic) NSString* _id;
/* User ID [optional]
 */
@property(nonatomic) NSString* uid;
/* Device Type ID [optional]
 */
@property(nonatomic) NSString* dtid;
/* Name [optional]
 */
@property(nonatomic) NSString* name;
/* Manifest Version [optional]
 */
@property(nonatomic) NSNumber* manifestVersion;
/* Manifest Version Policy (LATEST, DEVICE) [optional]
 */
@property(nonatomic) NSString* manifestVersionPolicy;
/* Needs Provider Authentication [optional]
 */
@property(nonatomic) NSNumber* needProviderAuth;

@property(nonatomic) NSDictionary<NSString*, NSObject*>* properties;
/* Created On (milliseconds since epoch) [optional]
 */
@property(nonatomic) NSNumber* createdOn;
/* Is Connected [optional]
 */
@property(nonatomic) NSNumber* connected;
/* Certificate Info (if any) [optional]
 */
@property(nonatomic) NSString* certificateInfo;
/* Certificate Signature (if any) [optional]
 */
@property(nonatomic) NSString* certificateSignature;
/* External ID (if any) [optional]
 */
@property(nonatomic) NSString* eid;

@property(nonatomic) NSDictionary<NSString*, NSObject*>* providerCredentials;

@end
