#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACActionDetails
@end

@interface ACActionDetails : ACObject

/* Parameters. [optional]
 */
@property(nonatomic) NSDictionary* /* NSString, NSObject */ parameters;
/* Name. [optional]
 */
@property(nonatomic) NSString* name;

@end
