#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACAcknowledgement
@end

@interface ACAcknowledgement : ACObject

/* Message ID. [optional]
 */
@property(nonatomic) NSString* mid;
/* Confirmation ID. [optional]
 */
@property(nonatomic) NSString* cid;
/* Message. [optional]
 */
@property(nonatomic) NSString* message;
/* Code [optional]
 */
@property(nonatomic) NSString* code;

@end
