#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACAggregatesHistogramData
@end

@interface ACAggregatesHistogramData : ACObject


@property(nonatomic) NSNumber* count;

@property(nonatomic) NSNumber* max;

@property(nonatomic) NSNumber* mean;

@property(nonatomic) NSNumber* min;

@property(nonatomic) NSNumber* sum;

@property(nonatomic) NSNumber* ts;

@property(nonatomic) NSNumber* variance;

@end
