#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ACAggregatesHistogramData.h"


@protocol ACAggregatesHistogramResponse
@end

@interface ACAggregatesHistogramResponse : ACObject


@property(nonatomic) NSArray<ACAggregatesHistogramData>* data;

@property(nonatomic) NSNumber* endDate;

@property(nonatomic) NSString* field;

@property(nonatomic) NSString* interval;

@property(nonatomic) NSString* sdid;

@property(nonatomic) NSNumber* size;

@property(nonatomic) NSNumber* startDate;

@end
