#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACAppProperties
@end

@interface ACAppProperties : ACObject


@property(nonatomic) NSString* uid;

@property(nonatomic) NSString* aid;

@property(nonatomic) NSString* properties;

@end
