#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACDeviceRegConfirmUserRequest
@end

@interface ACDeviceRegConfirmUserRequest : ACObject

/* Device ID. Optional if deviceName is present [optional]
 */
@property(nonatomic) NSString* deviceId;
/* Device Name. Optional if deviceId is present [optional]
 */
@property(nonatomic) NSString* deviceName;
/* Pin obtained in the registrations call. [optional]
 */
@property(nonatomic) NSString* pin;

@end
