#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ACDeviceType.h"


@protocol ACDeviceTypeEnvelope
@end

@interface ACDeviceTypeEnvelope : ACObject


@property(nonatomic) ACDeviceType* data;

@end
