#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACDeviceToken
@end

@interface ACDeviceToken : ACObject


@property(nonatomic) NSString* accessToken;

@property(nonatomic) NSString* uid;

@property(nonatomic) NSString* did;

@property(nonatomic) NSString* cid;

@end
