#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ACDeviceArray.h"


@protocol ACDevicesEnvelope
@end

@interface ACDevicesEnvelope : ACObject


@property(nonatomic) NSNumber* total;

@property(nonatomic) NSNumber* count;

@property(nonatomic) NSNumber* offset;

@property(nonatomic) ACDeviceArray* data;

@end
