#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ACDevice.h"


@protocol ACDeviceEnvelope
@end

@interface ACDeviceEnvelope : ACObject


@property(nonatomic) ACDevice* data;

@end
