#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ACDeviceType.h"


@protocol ACDeviceTypeArray
@end

@interface ACDeviceTypeArray : ACObject


@property(nonatomic) NSArray<ACDeviceType>* deviceTypes;

@end
