#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACDeviceRegCompleteRequest
@end

@interface ACDeviceRegCompleteRequest : ACObject

/* Nonce obtained from the initial registration request. [optional]
 */
@property(nonatomic) NSString* nonce;

@end
