#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACDeviceRegStatusResponse
@end

@interface ACDeviceRegStatusResponse : ACObject

/* The created or existing device id. [optional]
 */
@property(nonatomic) NSString* did;
/* Status of the ongoing device registration request. [optional]
 */
@property(nonatomic) NSString* status;

@end
