#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACDevice
@end

@interface ACDevice : ACObject

/* Device ID [optional]
 */
@property(nonatomic) NSString* _id;
/* User ID [optional]
 */
@property(nonatomic) NSString* uid;
/* Device Type ID [optional]
 */
@property(nonatomic) NSString* dtid;
/* Name [optional]
 */
@property(nonatomic) NSString* name;
/* Manifest Version [optional]
 */
@property(nonatomic) NSNumber* manifestVersion;
/* Manifest Version Policy (LATEST, DEVICE) [optional]
 */
@property(nonatomic) NSString* manifestVersionPolicy;
/* Needs Provider Authentication [optional]
 */
@property(nonatomic) NSNumber* needProviderAuth;

@property(nonatomic) NSDictionary* /* NSString, NSObject */ properties;
/* Created On (milliseconds since epoch) [optional]
 */
@property(nonatomic) NSNumber* createdOn;
/* Is Connected [optional]
 */
@property(nonatomic) NSNumber* connected;
/* Certificate Info (if any) [optional]
 */
@property(nonatomic) NSString* certificateInfo;
/* Certificate Signature (if any) [optional]
 */
@property(nonatomic) NSString* certificateSignature;
/* External ID (if any) [optional]
 */
@property(nonatomic) NSString* eid;

@property(nonatomic) NSDictionary* /* NSString, NSObject */ providerCredentials;

@end
