#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ACWebSocketError.h"


@protocol ACErrorEnvelope
@end

@interface ACErrorEnvelope : ACObject

/* Error Data [optional]
 */
@property(nonatomic) ACWebSocketError* error;

@end
