#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ACExportData.h"


@protocol ACExportDataArray
@end

@interface ACExportDataArray : ACObject


@property(nonatomic) NSArray<ACExportData>* exports;

@end
