#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACExportRequest
@end

@interface ACExportRequest : ACObject


@property(nonatomic) NSNumber* endDate;

@property(nonatomic) NSString* format;

@property(nonatomic) NSString* order;

@property(nonatomic) NSString* sdids;

@property(nonatomic) NSString* sdtids;

@property(nonatomic) NSNumber* startDate;

@property(nonatomic) NSString* trialId;

@property(nonatomic) NSString* uids;

@end
