#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACExportNormalizedMessagesResponse
@end

@interface ACExportNormalizedMessagesResponse : ACObject


@property(nonatomic) NSNumber* csvHeaders;

@property(nonatomic) NSNumber* endDate;

@property(nonatomic) NSString* exportId;

@property(nonatomic) NSString* format;

@property(nonatomic) NSString* order;

@property(nonatomic) NSString* sdid;

@property(nonatomic) NSString* sdids;

@property(nonatomic) NSNumber* startDate;

@property(nonatomic) NSString* stdids;

@property(nonatomic) NSString* trialId;

@property(nonatomic) NSString* uid;

@property(nonatomic) NSString* uids;

@property(nonatomic) NSString* url;

@end
