#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACExportStatusResponse
@end

@interface ACExportStatusResponse : ACObject


@property(nonatomic) NSNumber* expirationDate;

@property(nonatomic) NSString* exportId;

@property(nonatomic) NSString* md5;
/* Export status [optional]
 */
@property(nonatomic) NSString* status;

@property(nonatomic) NSString* ttl;

@end
