#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACExportResponse
@end

@interface ACExportResponse : ACObject

/* Add header to csv format [optional]
 */
@property(nonatomic) NSNumber* csvHeaders;
/* Timestamp of latest message (in milliseconds since epoch). [optional]
 */
@property(nonatomic) NSNumber* endDate;
/* Returned Export ID that should be used to check status and get the export result. [optional]
 */
@property(nonatomic) NSString* exportId;
/* Format of the export. [optional]
 */
@property(nonatomic) NSString* format;
/* Ascending or descending sort order. [optional]
 */
@property(nonatomic) NSString* order;
/* Source Device IDs being searched for messages (Comma-separated for multiple Device IDs). [optional]
 */
@property(nonatomic) NSString* sdids;
/* Source Device Type IDs being searched for messages (Comma-separated for multiple Device Type IDs). [optional]
 */
@property(nonatomic) NSString* sdtids;
/* Timestamp of earliest message (in milliseconds since epoch). [optional]
 */
@property(nonatomic) NSNumber* startDate;
/* Trial ID being searched for messages. [optional]
 */
@property(nonatomic) NSString* trialId;
/* Owner's user IDs being searched for messages (Comma-separated for multiple User IDs). [optional]
 */
@property(nonatomic) NSString* uids;
/* URL added to successful email message. [optional]
 */
@property(nonatomic) NSString* url;

@end
