#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ACExportDataArray.h"


@protocol ACExportHistoryResponse
@end

@interface ACExportHistoryResponse : ACObject


@property(nonatomic) NSNumber* count;

@property(nonatomic) ACExportDataArray* data;

@property(nonatomic) NSNumber* offset;

@property(nonatomic) NSNumber* total;

@end
