#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACFieldPresence
@end

@interface ACFieldPresence : ACObject


@property(nonatomic) NSNumber* startDate;

@end
