#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACFieldsActions
@end

@interface ACFieldsActions : ACObject

/* Message Fields [optional]
 */
@property(nonatomic) NSDictionary* /* NSString, NSObject */ fields;
/* Actions [optional]
 */
@property(nonatomic) NSDictionary* /* NSString, NSObject */ actions;

@end
