#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ACNonEmptyString.h"


@protocol ACFieldPath
@end

@interface ACFieldPath : ACObject


@property(nonatomic) NSArray<ACNonEmptyString>* path;

@end
