#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACMessageID
@end

@interface ACMessageID : ACObject

/* Message ID. [optional]
 */
@property(nonatomic) NSString* mid;

@end
