#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACMessageIn
@end

@interface ACMessageIn : ACObject

/* Message Payload. [optional]
 */
@property(nonatomic) NSDictionary* /* NSString, NSObject */ data;
/* Confirmation ID. [optional]
 */
@property(nonatomic) NSString* cid;
/* Destination Device ID. [optional]
 */
@property(nonatomic) NSString* ddid;
/* Source Device ID. [optional]
 */
@property(nonatomic) NSString* sdid;
/* Timestamp (past, present or future). Defaults to current time if not provided. [optional]
 */
@property(nonatomic) NSNumber* ts;
/* Type. [optional]
 */
@property(nonatomic) NSString* type;

@end
