#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ACNormalizedMessage.h"


@protocol ACNormalizedMessagesEnvelope
@end

@interface ACNormalizedMessagesEnvelope : ACObject


@property(nonatomic) NSString* sdids;

@property(nonatomic) NSString* sdid;

@property(nonatomic) NSString* uid;

@property(nonatomic) NSNumber* startDate;

@property(nonatomic) NSNumber* endDate;

@property(nonatomic) NSString* order;

@property(nonatomic) NSString* next;

@property(nonatomic) NSNumber* count;

@property(nonatomic) NSNumber* size;

@property(nonatomic) NSArray<ACNormalizedMessage>* data;

@end
