#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ACRuleError.h"
#import "ACRuleWarningOutput.h"


@protocol ACOutputRule
@end

@interface ACOutputRule : ACObject


@property(nonatomic) NSString* aid;

@property(nonatomic) NSNumber* createdOn;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSNumber* enabled;

@property(nonatomic) ACRuleError* error;

@property(nonatomic) NSString* _id;

@property(nonatomic) NSNumber* index;

@property(nonatomic) NSNumber* invalidatedOn;

@property(nonatomic) NSNumber* languageVersion;

@property(nonatomic) NSNumber* modifiedOn;

@property(nonatomic) NSString* name;

@property(nonatomic) NSDictionary* /* NSString, NSObject */ rule;

@property(nonatomic) NSString* uid;

@property(nonatomic) ACRuleWarningOutput* warning;

@end
