#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACRegisterMessage
@end

@interface ACRegisterMessage : ACObject

/* Confirmation ID. [optional]
 */
@property(nonatomic) NSString* cid;
/* Authorization header containing access token (Bearer <access_token>). [optional]
 */
@property(nonatomic) NSString* authorization;
/* Source Device ID. [optional]
 */
@property(nonatomic) NSString* sdid;
/* Timestamp (past, present or future). Defaults to current time if not provided. [optional]
 */
@property(nonatomic) NSNumber* ts;
/* Type. [optional]
 */
@property(nonatomic) NSString* type;

@end
