#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACRefreshTokenResponse
@end

@interface ACRefreshTokenResponse : ACObject


@property(nonatomic) NSString* accessToken;

@property(nonatomic) NSNumber* expiresIn;

@property(nonatomic) NSString* refreshToken;

@property(nonatomic) NSString* tokenType;

@end
