#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ACRuleArray.h"


@protocol ACRulesEnvelope
@end

@interface ACRulesEnvelope : ACObject


@property(nonatomic) NSNumber* count;

@property(nonatomic) ACRuleArray* data;

@property(nonatomic) NSNumber* offset;

@property(nonatomic) NSNumber* total;

@end
