#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACRuleUpdateInfo
@end

@interface ACRuleUpdateInfo : ACObject

/* Description [optional]
 */
@property(nonatomic) NSString* _description;
/* Is Enabled [optional]
 */
@property(nonatomic) NSNumber* enabled;
/* Name [optional]
 */
@property(nonatomic) NSString* name;
/* Rule [optional]
 */
@property(nonatomic) NSDictionary* /* NSString, NSObject */ rule;

@end
