#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ACOutputRule.h"


@protocol ACRuleArray
@end

@interface ACRuleArray : ACObject


@property(nonatomic) NSArray<ACOutputRule>* rules;

@end
