#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ACFieldPath.h"


@protocol ACRuleError
@end

@interface ACRuleError : ACObject


@property(nonatomic) NSNumber* errorCode;

@property(nonatomic) ACFieldPath* fieldPath;

@property(nonatomic) NSArray* /* NSString */ messageArgs;

@property(nonatomic) NSString* messageKey;

@end
