#import <Foundation/Foundation.h>
#import "ACTagsEnvelope.h"
#import "ACObject.h"
#import "ACApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface ACTagsApi: NSObject

@property(nonatomic, assign)ACApiClient *apiClient;

-(instancetype) initWithApiClient:(ACApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(ACTagsApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(ACTagsApi*) sharedAPI;
///
///
/// Get all tags of categories
/// Get all tags related to the list of categories
///
/// @param categories Comma separated list of categories.
/// 
///
/// @return ACTagsEnvelope*
-(NSNumber*) getTagsByCategoriesWithCategories: (NSString*) categories
    completionHandler: (void (^)(ACTagsEnvelope* output, NSError* error)) handler;


///
///
/// Get all categories
/// Get all tags marked as categories
///
/// 
///
/// @return ACTagsEnvelope*
-(NSNumber*) getTagCategoriesWithCompletionHandler: 
    (void (^)(ACTagsEnvelope* output, NSError* error)) handler;


///
///
/// Get tag suggestions
/// Get tag suggestions for applications, device types that have been most used with a group of tags.
///
/// @param entityType Entity type name.
/// @param tags Comma separated list of tags.
/// @param name Name of tags used for type ahead.
/// @param count Number of results to return. Max 10.
/// 
///
/// @return ACTagsEnvelope*
-(NSNumber*) getTagSuggestionsWithEntityType: (NSString*) entityType
    tags: (NSString*) tags
    name: (NSString*) name
    count: (NSNumber*) count
    completionHandler: (void (^)(ACTagsEnvelope* output, NSError* error)) handler;



@end
