#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACTag
@end

@interface ACTag : ACObject

/* Tag Name. [optional]
 */
@property(nonatomic) NSString* name;
/* Is Category. [optional]
 */
@property(nonatomic) NSNumber* isCategory;

@end
