#import <Foundation/Foundation.h>
#import "ACTokenRequest.h"
#import "ACCheckTokenResponse.h"
#import "ACRefreshTokenResponse.h"
#import "ACObject.h"
#import "ACApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface ACTokensApi: NSObject

@property(nonatomic, assign)ACApiClient *apiClient;

-(instancetype) initWithApiClient:(ACApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(ACTokensApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(ACTokensApi*) sharedAPI;
///
///
/// Check Token
/// Check Token
///
/// @param tokenInfo Token object to be checked
/// 
///
/// @return ACCheckTokenResponse*
-(NSNumber*) checkTokenWithTokenInfo: (ACTokenRequest*) tokenInfo
    completionHandler: (void (^)(ACCheckTokenResponse* output, NSError* error)) handler;


///
///
/// Refresh Token
/// Refresh Token
///
/// @param grantType Grant Type.
/// @param refreshToken Refresh Token.
/// 
///
/// @return ACRefreshTokenResponse*
-(NSNumber*) refreshTokenWithGrantType: (NSString*) grantType
    refreshToken: (NSString*) refreshToken
    completionHandler: (void (^)(ACRefreshTokenResponse* output, NSError* error)) handler;



@end
