#import <Foundation/Foundation.h>
#import "ACObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ACUnregisterDeviceResponse
@end

@interface ACUnregisterDeviceResponse : ACObject

/* Device certificate information. [optional]
 */
@property(nonatomic) NSString* certificateInfo;
/* Certificate's signature. [optional]
 */
@property(nonatomic) NSString* certificateSignature;
/* Device created on date. [optional]
 */
@property(nonatomic) NSNumber* createdOn;
/* Device type id. [optional]
 */
@property(nonatomic) NSString* dtid;
/* External ID of the device. [optional]
 */
@property(nonatomic) NSString* eid;
/* Device id. [optional]
 */
@property(nonatomic) NSString* _id;
/* Device manifest version. [optional]
 */
@property(nonatomic) NSNumber* manifestVersion;
/* Device manifest version policy. [optional]
 */
@property(nonatomic) NSString* manifestVersionPolicy;
/* Device name. [optional]
 */
@property(nonatomic) NSString* name;
/* Device need provider auth. [optional]
 */
@property(nonatomic) NSNumber* needProviderAuth;
/* User id. [optional]
 */
@property(nonatomic) NSString* uid;

@end
