#import <Foundation/Foundation.h>
#import "ACDeviceRegConfirmUserResponseEnvelope.h"
#import "ACDeviceRegConfirmUserRequest.h"
#import "ACDeviceRegStatusResponseEnvelope.h"
#import "ACUnregisterDeviceResponseEnvelope.h"
#import "ACApi.h"

/**
* ARTIK Cloud API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface ACRegistrationsApi: NSObject <ACApi>

extern NSString* kACRegistrationsApiErrorDomain;
extern NSInteger kACRegistrationsApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Confirm User
/// This call updates the registration request issued earlier by associating it with an authenticated user and captures all additional information required to add a new device.
///
/// @param registrationInfo Device Registration information.
/// 
///  code:0 message:"success"
///
/// @return ACDeviceRegConfirmUserResponseEnvelope*
-(NSNumber*) confirmUserWithRegistrationInfo: (ACDeviceRegConfirmUserRequest*) registrationInfo
    completionHandler: (void (^)(ACDeviceRegConfirmUserResponseEnvelope* output, NSError* error)) handler;


/// Get Request Status For User
/// This call checks the status of the request so users can poll and know when registration is complete.
///
/// @param requestId Request ID.
/// 
///  code:0 message:"success"
///
/// @return ACDeviceRegStatusResponseEnvelope*
-(NSNumber*) getRequestStatusForUserWithRequestId: (NSString*) requestId
    completionHandler: (void (^)(ACDeviceRegStatusResponseEnvelope* output, NSError* error)) handler;


/// Unregister Device
/// This call clears any associations from the secure device registration.
///
/// @param deviceId Device ID.
/// 
///  code:0 message:"success"
///
/// @return ACUnregisterDeviceResponseEnvelope*
-(NSNumber*) unregisterDeviceWithDeviceId: (NSString*) deviceId
    completionHandler: (void (^)(ACUnregisterDeviceResponseEnvelope* output, NSError* error)) handler;



@end
