#import <Foundation/Foundation.h>
#import "ACTagsEnvelope.h"
#import "ACApi.h"

/**
* ARTIK Cloud API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface ACTagsApi: NSObject <ACApi>

extern NSString* kACTagsApiErrorDomain;
extern NSInteger kACTagsApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Get all categories
/// Get all tags marked as categories
///
/// 
///  code:0 message:"success"
///
/// @return ACTagsEnvelope*
-(NSNumber*) getTagCategoriesWithCompletionHandler: 
    (void (^)(ACTagsEnvelope* output, NSError* error)) handler;


/// Get tag suggestions
/// Get tag suggestions for applications, device types that have been most used with a group of tags.
///
/// @param entityType Entity type name. (optional)
/// @param tags Comma separated list of tags. (optional)
/// @param name Name of tags used for type ahead. (optional)
/// @param count Number of results to return. Max 10. (optional)
/// 
///  code:0 message:"success"
///
/// @return ACTagsEnvelope*
-(NSNumber*) getTagSuggestionsWithEntityType: (NSString*) entityType
    tags: (NSString*) tags
    name: (NSString*) name
    count: (NSNumber*) count
    completionHandler: (void (^)(ACTagsEnvelope* output, NSError* error)) handler;


/// Get all tags of categories
/// Get all tags related to the list of categories
///
/// @param categories Comma separated list of categories. (optional)
/// 
///  code:0 message:"success"
///
/// @return ACTagsEnvelope*
-(NSNumber*) getTagsByCategoriesWithCategories: (NSString*) categories
    completionHandler: (void (^)(ACTagsEnvelope* output, NSError* error)) handler;



@end
