#import <Foundation/Foundation.h>
#import "ACPropertiesEnvelope.h"
#import "ACAppProperties.h"
#import "ACUserEnvelope.h"
#import "ACDeviceTypesEnvelope.h"
#import "ACDevicesEnvelope.h"
#import "ACRulesEnvelope.h"
#import "ACApi.h"

/**
* ARTIK Cloud API
* No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface ACUsersApi: NSObject <ACApi>

extern NSString* kACUsersApiErrorDomain;
extern NSInteger kACUsersApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Create User Application Properties
/// Create application properties for a user
///
/// @param userId User Id
/// @param properties Properties to be updated
/// @param aid Application ID (optional)
/// 
///  code:0 message:"success"
///
/// @return ACPropertiesEnvelope*
-(NSNumber*) createUserPropertiesWithUserId: (NSString*) userId
    properties: (ACAppProperties*) properties
    aid: (NSString*) aid
    completionHandler: (void (^)(ACPropertiesEnvelope* output, NSError* error)) handler;


/// Delete User Application Properties
/// Deletes a user's application properties
///
/// @param userId User Id
/// @param aid Application ID (optional)
/// 
///  code:0 message:"success"
///
/// @return ACPropertiesEnvelope*
-(NSNumber*) deleteUserPropertiesWithUserId: (NSString*) userId
    aid: (NSString*) aid
    completionHandler: (void (^)(ACPropertiesEnvelope* output, NSError* error)) handler;


/// Get Current User Profile
/// Get's the current user's profile
///
/// 
///  code:0 message:"success"
///
/// @return ACUserEnvelope*
-(NSNumber*) getSelfWithCompletionHandler: 
    (void (^)(ACUserEnvelope* output, NSError* error)) handler;


/// Get User Device Types
/// Retrieve User's Device Types
///
/// @param userId User ID.
/// @param offset Offset for pagination. (optional)
/// @param count Desired count of items in the result set (optional)
/// @param includeShared Optional. Boolean (true/false) - If false, only return the user&#39;s device types. If true, also return device types shared by other users. (optional)
/// 
///  code:0 message:"success"
///
/// @return ACDeviceTypesEnvelope*
-(NSNumber*) getUserDeviceTypesWithUserId: (NSString*) userId
    offset: (NSNumber*) offset
    count: (NSNumber*) count
    includeShared: (NSNumber*) includeShared
    completionHandler: (void (^)(ACDeviceTypesEnvelope* output, NSError* error)) handler;


/// Get User Devices
/// Retrieve User's Devices
///
/// @param userId User ID
/// @param offset Offset for pagination. (optional)
/// @param count Desired count of items in the result set (optional)
/// @param includeProperties Optional. Boolean (true/false) - If false, only return the user&#39;s device types. If true, also return device types shared by other users. (optional)
/// 
///  code:0 message:"success"
///
/// @return ACDevicesEnvelope*
-(NSNumber*) getUserDevicesWithUserId: (NSString*) userId
    offset: (NSNumber*) offset
    count: (NSNumber*) count
    includeProperties: (NSNumber*) includeProperties
    completionHandler: (void (^)(ACDevicesEnvelope* output, NSError* error)) handler;


/// Get User application properties
/// Get application properties of a user
///
/// @param userId User Id
/// @param aid Application ID (optional)
/// 
///  code:0 message:"success"
///
/// @return ACPropertiesEnvelope*
-(NSNumber*) getUserPropertiesWithUserId: (NSString*) userId
    aid: (NSString*) aid
    completionHandler: (void (^)(ACPropertiesEnvelope* output, NSError* error)) handler;


/// Get User Rules
/// Retrieve User's Rules
///
/// @param userId User ID.
/// @param excludeDisabled Exclude disabled rules in the result. (optional)
/// @param count Desired count of items in the result set. (optional)
/// @param offset Offset for pagination. (optional)
/// 
///  code:0 message:"success"
///
/// @return ACRulesEnvelope*
-(NSNumber*) getUserRulesWithUserId: (NSString*) userId
    excludeDisabled: (NSNumber*) excludeDisabled
    count: (NSNumber*) count
    offset: (NSNumber*) offset
    completionHandler: (void (^)(ACRulesEnvelope* output, NSError* error)) handler;


/// Update User Application Properties
/// Updates application properties of a user
///
/// @param userId User Id
/// @param properties Properties to be updated
/// @param aid Application ID (optional)
/// 
///  code:0 message:"success"
///
/// @return ACPropertiesEnvelope*
-(NSNumber*) updateUserPropertiesWithUserId: (NSString*) userId
    properties: (ACAppProperties*) properties
    aid: (NSString*) aid
    completionHandler: (void (^)(ACPropertiesEnvelope* output, NSError* error)) handler;



@end
